name: Secure Backup and Upload

on:
  workflow_dispatch: 
  schedule:
    - cron: '15 12 * * *'

jobs:
  backup-and-upload:
    runs-on: self-hosted
    steps:
      - name: Show Current Time
        run: date
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Export Database
        run: |
          mysqldump -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} concierto -h 10.0.1.4 > database_backup.sql

      - name: Upload to Azure Storage
        run: |
          az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --container-name backup --file ./database_backup.sql --name "database_backup_$(date +%Y%m%d%H%M%S).sql"
